name: "新機能提案・要望 - Enhancement"
description: 新しい機能・プラグイン等の提案・要望がある場合は、このテンプレートを使用してください。
labels: ["✨enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        jao Community の Web サイト([`jaoafa/jaoweb`](https://github.com/jaoafa/jaoweb))、MyMaid4([`jaoafa/MyMaid4`](https://github.com/jaoafa/MyMaid4)) および Javajaotan2([`jaoafa/Javajaotan2`](https://github.com/jaoafa/Javajaotan2)) の不具合報告や新機能の提案は各リポジトリの Issue にてお願いします。
        Issue の提出先が間違っていても、メンテナーが移動しますのでご安心ください。
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 新機能について、理由も併せて明確・簡潔に説明してください。またそれを希望する理由もお書きください。
    validations:
      required: true
