name: "既存機能の強化・改善提案・要望 - Improvement"
description: 既にある機能の強化や改善の提案・要望がある場合は、このテンプレートを使用してください。
labels: ["♻improvement"]
body:
- type: markdown
  attributes:
    value: |
      jao Minecraft Server の Web サイト([`jaoafa/jaoweb`](https://github.com/jaoafa/jaoweb))、MyMaid4([`jaoafa/MyMaid4`](https://github.com/jaoafa/MyMaid4)) および Javajaotan2([`jaoafa/Javajaotan2`](https://github.com/jaoafa/Javajaotan2)) の不具合報告や新機能の提案は各リポジトリの Issue にてお願いします。
      Issue の提出先が間違っていても、メンテナーが移動しますのでご安心ください。
- type: textarea
  id: target
  attributes:
    label: 対象の機能
    description: どの機能に対するものかを示してください。
    render: markdown
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: 強化・改善の内容
    description: どのように強化・改善を行うかを示してください。またそれを希望する理由もお書きください。
    render: markdown
  validations:
    required: true
